### ISSUE TITLE
djghjc 

### ISSUE THREAD

**Issue by jrer4564343** [benjee10/Benjee10_MMSEV#1]
when can you release the mod release ?

**Comment by benjee10** [comment]
The mod will be released when it's ready.

**Comment by jrer4564343** [comment]
will there be a greenhouse for life support mods in fashion ?
do you know about the problem when docking the base modules on the planet after separation, the part simply flies away from the base ?

**Comment by jrer4564343** [comment]
Есть предложения можешь когда мод выйдет релиз, сделать переводчик текста на руский или на другии языки,да знаю это займёт больше времени и ресурсов.

**Comment by jrer4564343** [comment]
There are suggestions that you can make a text translator into Russian or other languages when the mod is released, but I know it will take more time and resources.
