### ISSUE TITLE
TAC Life Support isn't working

### ISSUE THREAD

**Issue by cwashington1217** [benjee10/Benjee10_MMSEV#7]
I have been playing with TAC for some time now and was excited to see this mod has compatibility. when i downloaded it and installed it, it didn't show and signs of TAC implementation am I missing something or has it not been implemented.

**Comment by cwashington1217** [comment]
nevermind bug caused in my part its working properly now

**Comment by lucbk** [comment]
I updated the module manager patch. Now parts have the appropriate life support amounts and converters/recyclers are available #9.
